platform :ios, '7.0' 

def import_pods
	pod "ArchaicProtocols", :path => "../"
end

target "Example", :exclusive => true do
	import_pods
	link_with "Example"
end

target "ExampleTests", :exclusive => true do
	import_pods
	link_with "ExampleTests"
end
